export const DB_PASSWORD = "DB_PASSWORD";
export const DB_USER = "DB_USER";
export const DB_HOST = "DB_HOST";
export const DB_PORT = "DB_PORT";
export const DB_DATABASE = "DB_DATABASE";


export const API_HOST = "API_HOST";
export const API_PORT = "API_PORT";
export const API_ROOT = "API_ROOT";


export const JWT_VERIFICATION_SECRET="JWT_VERIFICATION_SECRET";
export const JWT_VERIFICATION_EXPIRATION_TIME="JWT_VERIFICATION_EXPIRATION_TIME";

export const JWT_ACCESS_SECRET="JWT_ACCESS_SECRET";
export const JWT_ACCESS_EXPIRATION_TIME="JWT_ACCESS_EXPIRATION_TIME";

export const JWT_REFRESH_SECRET="JWT_REFRESH_SECRET";
export const JWT_REFRESH_EXPIRATION_TIME="JWT_REFRESH_EXPIRATION_TIME";


export const HASH_ALGORITHM="HASH_ALGORITHM";
export const SALT_LENGTH="SALT_LENGTH";
export const HASH_LENGTH="HASH_LENGTH";
export const ENCRYPTION_ALGORITHM="ENCRYPTION_ALGORITHM";
export const SALT_SECRET="SALT_SECRET";
export const IV_LENGTH="IV_LENGTH";