name: CICD for K-link

on:
  push: 
    branches: ['main']
  pull_request:
    branches: ['main']
    
jobs:
  js-code:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        
      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: 22.17.0
          cache: npm
        
      - name: Install deps
        run: npm ci
       
      - name: Linting
        run: npm run lint
      
      - name: Run Unit tests
        run: npm test 
      
