name: CICD for K-link

on:
  push: 
  pull_request:
    
jobs:
  js-code:
    runs-on: ubuntu-latest
    container: node:22-slim
    permissions:
      contents: read
      
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        
      - name: Install deps
        run: npm ci
        working-directory: ./api
       
      - name: Build
        run: npm run build
        working-directory: ./api
        
      - name: Linting
        run: npm run lint
        working-directory: ./api
      
      - name: Run Unit tests
        run: npm run test 
        working-directory: ./api
  
